// Base de datos de alimentos
// kcal_por_unidad: si unidad="g" -> kcal por 100g; si unidad="ud" -> kcal por unidad
// Datos basados en tablas nutricionales estándar (USDA, BEDCA)

const ALIMENTOS_RAPIDOS = [
  // Frutas (15)
  {n:"Manzana", u:"g", kcal:52, ref:100},
  {n:"Plátano", u:"g", kcal:89, ref:100},
  {n:"Naranja", u:"g", kcal:47, ref:100},
  {n:"Pera", u:"g", kcal:57, ref:100},
  {n:"Fresas", u:"g", kcal:32, ref:100},
  {n:"Uvas", u:"g", kcal:69, ref:100},
  {n:"Kiwi", u:"g", kcal:61, ref:100},
  {n:"Piña", u:"g", kcal:50, ref:100},
  {n:"Sandía", u:"g", kcal:30, ref:100},
  {n:"Melón", u:"g", kcal:34, ref:100},
  {n:"Mandarina", u:"g", kcal:53, ref:100},
  {n:"Melocotón", u:"g", kcal:39, ref:100},
  {n:"Ciruela", u:"g", kcal:46, ref:100},
  {n:"Aguacate", u:"g", kcal:160, ref:100},
  {n:"Arándanos", u:"g", kcal:57, ref:100},
  // Verduras (15)
  {n:"Tomate", u:"g", kcal:18, ref:100},
  {n:"Lechuga", u:"g", kcal:15, ref:100},
  {n:"Pepino", u:"g", kcal:16, ref:100},
  {n:"Zanahoria", u:"g", kcal:41, ref:100},
  {n:"Pimiento rojo", u:"g", kcal:31, ref:100},
  {n:"Pimiento verde", u:"g", kcal:20, ref:100},
  {n:"Cebolla", u:"g", kcal:40, ref:100},
  {n:"Ajo", u:"g", kcal:149, ref:100},
  {n:"Brócoli", u:"g", kcal:34, ref:100},
  {n:"Coliflor", u:"g", kcal:25, ref:100},
  {n:"Espinacas", u:"g", kcal:23, ref:100},
  {n:"Calabacín", u:"g", kcal:17, ref:100},
  {n:"Berenjena", u:"g", kcal:25, ref:100},
  {n:"Judías verdes", u:"g", kcal:31, ref:100},
  {n:"Champiñones", u:"g", kcal:22, ref:100},
  // Cereales y pan (12)
  {n:"Pan blanco", u:"g", kcal:265, ref:100},
  {n:"Pan integral", u:"g", kcal:247, ref:100},
  {n:"Pan de semillas (Lidl Campeón)", u:"g", kcal:260, ref:100},
  {n:"Tostada pan semillas 10mm (~25g)", u:"ud", kcal:65},
  {n:"Arroz blanco cocido", u:"g", kcal:130, ref:100},
  {n:"Arroz integral cocido", u:"g", kcal:111, ref:100},
  {n:"Pasta cocida", u:"g", kcal:131, ref:100},
  {n:"Pasta integral cocida", u:"g", kcal:124, ref:100},
  {n:"Avena copos", u:"g", kcal:389, ref:100},
  {n:"Cereales All-Bran", u:"g", kcal:334, ref:100},
  {n:"Quinoa cocida", u:"g", kcal:120, ref:100},
  {n:"Tortita arroz/maíz", u:"ud", kcal:25},
  // Lácteos (10)
  {n:"Leche entera", u:"g", kcal:61, ref:100},
  {n:"Leche semidesnatada", u:"g", kcal:46, ref:100},
  {n:"Leche desnatada", u:"g", kcal:34, ref:100},
  {n:"Yogur natural", u:"g", kcal:59, ref:100},
  {n:"Yogur desnatado", u:"g", kcal:43, ref:100},
  {n:"Yogur griego natural", u:"g", kcal:97, ref:100},
  {n:"Queso fresco batido 0%", u:"g", kcal:50, ref:100},
  {n:"Queso curado", u:"g", kcal:370, ref:100},
  {n:"Queso fresco tipo Burgos", u:"g", kcal:174, ref:100},
  {n:"Requesón", u:"g", kcal:97, ref:100},
  // Proteínas animales (15)
  {n:"Huevo entero (M ~55g)", u:"ud", kcal:78},
  {n:"Clara de huevo", u:"g", kcal:52, ref:100},
  {n:"Pechuga pollo", u:"g", kcal:165, ref:100},
  {n:"Muslo pollo", u:"g", kcal:209, ref:100},
  {n:"Pavo pechuga", u:"g", kcal:135, ref:100},
  {n:"Ternera magra", u:"g", kcal:158, ref:100},
  {n:"Cerdo lomo", u:"g", kcal:143, ref:100},
  {n:"Jamón serrano", u:"g", kcal:241, ref:100},
  {n:"Jamón cocido", u:"g", kcal:108, ref:100},
  {n:"Atún en aceite escurrido", u:"g", kcal:200, ref:100},
  {n:"Atún al natural", u:"g", kcal:108, ref:100},
  {n:"Salmón", u:"g", kcal:208, ref:100},
  {n:"Merluza", u:"g", kcal:71, ref:100},
  {n:"Sardinas en aceite", u:"g", kcal:208, ref:100},
  {n:"Gambas", u:"g", kcal:99, ref:100},
  // Legumbres y frutos secos (10)
  {n:"Lentejas cocidas", u:"g", kcal:116, ref:100},
  {n:"Garbanzos cocidos", u:"g", kcal:164, ref:100},
  {n:"Alubias blancas cocidas", u:"g", kcal:127, ref:100},
  {n:"Soja texturizada seca", u:"g", kcal:340, ref:100},
  {n:"Almendras", u:"g", kcal:579, ref:100},
  {n:"Nueces", u:"g", kcal:654, ref:100},
  {n:"Avellanas", u:"g", kcal:628, ref:100},
  {n:"Pistachos", u:"g", kcal:560, ref:100},
  {n:"Cacahuetes", u:"g", kcal:567, ref:100},
  {n:"Anacardos", u:"g", kcal:553, ref:100},
  // Grasas y aceites (6)
  {n:"Aceite oliva virgen extra (AOVE)", u:"g", kcal:884, ref:100},
  {n:"Aceite girasol", u:"g", kcal:884, ref:100},
  {n:"Mantequilla", u:"g", kcal:717, ref:100},
  {n:"Margarina", u:"g", kcal:626, ref:100},
  {n:"Mayonesa", u:"g", kcal:680, ref:100},
  {n:"Aceitunas verdes", u:"g", kcal:145, ref:100},
  // Bebidas (10)
  {n:"Café solo (sin azúcar)", u:"ud", kcal:2},
  {n:"Café con leche desnatada (200ml)", u:"ud", kcal:24},
  {n:"Café con leche semidesnatada (200ml)", u:"ud", kcal:32},
  {n:"Café con leche entera (200ml)", u:"ud", kcal:40},
  {n:"Té/infusión sin azúcar", u:"ud", kcal:2},
  {n:"Zumo naranja natural", u:"g", kcal:45, ref:100},
  {n:"Refresco azucarado", u:"g", kcal:42, ref:100},
  {n:"Refresco light/zero", u:"g", kcal:1, ref:100},
  {n:"Cerveza", u:"g", kcal:43, ref:100},
  {n:"Vino tinto", u:"g", kcal:85, ref:100},
  // Otros (7)
  {n:"Patata cocida", u:"g", kcal:87, ref:100},
  {n:"Patata frita", u:"g", kcal:312, ref:100},
  {n:"Azúcar", u:"g", kcal:387, ref:100},
  {n:"Miel", u:"g", kcal:304, ref:100},
  {n:"Chocolate negro 70%", u:"g", kcal:546, ref:100},
  {n:"Galleta María", u:"ud", kcal:23},
  {n:"Tomate frito", u:"g", kcal:82, ref:100}
];

// Base personalizada con 1000+ alimentos
const ALIMENTOS_PERSONALIZADOS = [
  // ===== FRUTAS (80) =====
  {n:"Manzana golden", u:"g", kcal:52},
  {n:"Manzana fuji", u:"g", kcal:63},
  {n:"Manzana granny smith", u:"g", kcal:58},
  {n:"Manzana reineta", u:"g", kcal:56},
  {n:"Manzana royal gala", u:"g", kcal:55},
  {n:"Manzana asada sin azúcar", u:"g", kcal:55},
  {n:"Plátano de Canarias", u:"g", kcal:89},
  {n:"Plátano macho", u:"g", kcal:122},
  {n:"Banana", u:"g", kcal:89},
  {n:"Naranja", u:"g", kcal:47},
  {n:"Naranja sanguina", u:"g", kcal:50},
  {n:"Mandarina clementina", u:"g", kcal:53},
  {n:"Pomelo rosa", u:"g", kcal:42},
  {n:"Pomelo amarillo", u:"g", kcal:33},
  {n:"Limón", u:"g", kcal:29},
  {n:"Lima", u:"g", kcal:30},
  {n:"Pera conferencia", u:"g", kcal:57},
  {n:"Pera ercolini", u:"g", kcal:58},
  {n:"Pera williams", u:"g", kcal:58},
  {n:"Pera limonera", u:"g", kcal:55},
  {n:"Fresas", u:"g", kcal:32},
  {n:"Fresón", u:"g", kcal:35},
  {n:"Frambuesas", u:"g", kcal:52},
  {n:"Moras", u:"g", kcal:43},
  {n:"Arándanos azules", u:"g", kcal:57},
  {n:"Arándanos rojos", u:"g", kcal:46},
  {n:"Grosellas", u:"g", kcal:56},
  {n:"Uvas blancas", u:"g", kcal:69},
  {n:"Uvas negras", u:"g", kcal:70},
  {n:"Uvas pasas", u:"g", kcal:299},
  {n:"Kiwi verde", u:"g", kcal:61},
  {n:"Kiwi amarillo", u:"g", kcal:60},
  {n:"Piña natural", u:"g", kcal:50},
  {n:"Piña en almíbar", u:"g", kcal:78},
  {n:"Mango", u:"g", kcal:60},
  {n:"Papaya", u:"g", kcal:43},
  {n:"Maracuyá", u:"g", kcal:97},
  {n:"Guayaba", u:"g", kcal:68},
  {n:"Coco fresco", u:"g", kcal:354},
  {n:"Coco rallado", u:"g", kcal:660},
  {n:"Sandía", u:"g", kcal:30},
  {n:"Melón cantalupo", u:"g", kcal:34},
  {n:"Melón galia", u:"g", kcal:34},
  {n:"Melón piel sapo", u:"g", kcal:36},
  {n:"Melocotón", u:"g", kcal:39},
  {n:"Melocotón en almíbar", u:"g", kcal:74},
  {n:"Nectarina", u:"g", kcal:44},
  {n:"Albaricoque", u:"g", kcal:48},
  {n:"Albaricoque seco/orejones", u:"g", kcal:241},
  {n:"Ciruela roja", u:"g", kcal:46},
  {n:"Ciruela amarilla", u:"g", kcal:46},
  {n:"Ciruela pasa", u:"g", kcal:240},
  {n:"Cereza", u:"g", kcal:50},
  {n:"Picota", u:"g", kcal:55},
  {n:"Higo fresco", u:"g", kcal:74},
  {n:"Higo seco", u:"g", kcal:249},
  {n:"Dátil", u:"g", kcal:282},
  {n:"Caqui/persimon", u:"g", kcal:81},
  {n:"Granada", u:"g", kcal:83},
  {n:"Chirimoya", u:"g", kcal:75},
  {n:"Aguacate", u:"g", kcal:160},
  {n:"Aceitunas verdes", u:"g", kcal:145},
  {n:"Aceitunas negras", u:"g", kcal:115},
  {n:"Aceitunas rellenas anchoa", u:"g", kcal:150},
  {n:"Manzana entera (~180g)", u:"ud", kcal:94},
  {n:"Plátano entero (~120g sin piel)", u:"ud", kcal:107},
  {n:"Media banana grande (~75g)", u:"ud", kcal:67},
  {n:"Naranja entera mediana (~200g)", u:"ud", kcal:94},
  {n:"Mandarina (~80g)", u:"ud", kcal:42},
  {n:"Kiwi (~75g)", u:"ud", kcal:46},
  {n:"Pera (~170g)", u:"ud", kcal:97},
  {n:"Melocotón (~150g)", u:"ud", kcal:59},
  {n:"Ciruela (~60g)", u:"ud", kcal:28},
  {n:"Fresa (~12g)", u:"ud", kcal:4},
  {n:"Higo (~50g)", u:"ud", kcal:37},
  {n:"Dátil (~8g sin hueso)", u:"ud", kcal:23},
  {n:"Aguacate medio (~150g)", u:"ud", kcal:240},
  {n:"Tomate cherry (~10g)", u:"ud", kcal:2},
  {n:"Aceituna (~4g)", u:"ud", kcal:6},
  {n:"Granada mediana (~280g)", u:"ud", kcal:232},

  // ===== VERDURAS Y HORTALIZAS (90) =====
  {n:"Tomate rama", u:"g", kcal:18},
  {n:"Tomate pera", u:"g", kcal:18},
  {n:"Tomate cherry", u:"g", kcal:20},
  {n:"Tomate raf", u:"g", kcal:18},
  {n:"Tomate seco", u:"g", kcal:258},
  {n:"Tomate frito en conserva", u:"g", kcal:82},
  {n:"Tomate triturado natural", u:"g", kcal:22},
  {n:"Salsa tomate casera AOVE", u:"g", kcal:50},
  {n:"Lechuga iceberg", u:"g", kcal:14},
  {n:"Lechuga romana", u:"g", kcal:17},
  {n:"Lechuga hoja roble", u:"g", kcal:15},
  {n:"Canónigos", u:"g", kcal:21},
  {n:"Rúcula", u:"g", kcal:25},
  {n:"Endivias", u:"g", kcal:17},
  {n:"Escarola", u:"g", kcal:17},
  {n:"Berros", u:"g", kcal:11},
  {n:"Espinacas crudas", u:"g", kcal:23},
  {n:"Espinacas cocidas", u:"g", kcal:23},
  {n:"Acelgas", u:"g", kcal:19},
  {n:"Pepino", u:"g", kcal:16},
  {n:"Zanahoria cruda", u:"g", kcal:41},
  {n:"Zanahoria cocida", u:"g", kcal:35},
  {n:"Remolacha cocida", u:"g", kcal:43},
  {n:"Apio", u:"g", kcal:16},
  {n:"Hinojo", u:"g", kcal:31},
  {n:"Rábano", u:"g", kcal:16},
  {n:"Nabo", u:"g", kcal:28},
  {n:"Pimiento rojo", u:"g", kcal:31},
  {n:"Pimiento verde italiano", u:"g", kcal:20},
  {n:"Pimiento amarillo", u:"g", kcal:27},
  {n:"Pimiento padrón", u:"g", kcal:35},
  {n:"Pimiento del piquillo conserva", u:"g", kcal:44},
  {n:"Cebolla blanca", u:"g", kcal:40},
  {n:"Cebolla morada", u:"g", kcal:42},
  {n:"Cebolleta tierna", u:"g", kcal:32},
  {n:"Puerro", u:"g", kcal:61},
  {n:"Ajo crudo", u:"g", kcal:149},
  {n:"Ajos tiernos", u:"g", kcal:41},
  {n:"Brócoli", u:"g", kcal:34},
  {n:"Coliflor", u:"g", kcal:25},
  {n:"Coles de Bruselas", u:"g", kcal:43},
  {n:"Col lombarda", u:"g", kcal:31},
  {n:"Col rizada/kale", u:"g", kcal:35},
  {n:"Repollo", u:"g", kcal:25},
  {n:"Grelos", u:"g", kcal:21},
  {n:"Berza", u:"g", kcal:30},
  {n:"Calabacín", u:"g", kcal:17},
  {n:"Calabaza", u:"g", kcal:26},
  {n:"Berenjena", u:"g", kcal:25},
  {n:"Pepinillo en vinagre", u:"g", kcal:12},
  {n:"Judías verdes planas", u:"g", kcal:31},
  {n:"Judías verdes redondas", u:"g", kcal:31},
  {n:"Champiñones", u:"g", kcal:22},
  {n:"Setas portobello", u:"g", kcal:22},
  {n:"Setas shiitake", u:"g", kcal:34},
  {n:"Boletus", u:"g", kcal:34},
  {n:"Níscalos", u:"g", kcal:22},
  {n:"Espárragos verdes", u:"g", kcal:20},
  {n:"Espárragos blancos lata", u:"g", kcal:15},
  {n:"Alcachofa fresca", u:"g", kcal:47},
  {n:"Alcachofa corazón conserva", u:"g", kcal:55},
  {n:"Cardo", u:"g", kcal:17},
  {n:"Maíz dulce lata", u:"g", kcal:86},
  {n:"Guisantes frescos", u:"g", kcal:81},
  {n:"Guisantes congelados", u:"g", kcal:73},
  {n:"Habas frescas", u:"g", kcal:88},
  {n:"Edamame", u:"g", kcal:121},
  {n:"Soja germinada", u:"g", kcal:122},
  {n:"Brotes alfalfa", u:"g", kcal:23},
  {n:"Algas wakame", u:"g", kcal:45},
  {n:"Algas nori", u:"g", kcal:35},
  {n:"Jengibre fresco", u:"g", kcal:80},
  {n:"Patata cruda", u:"g", kcal:77},
  {n:"Patata cocida", u:"g", kcal:87},
  {n:"Patata asada", u:"g", kcal:93},
  {n:"Patata frita casera", u:"g", kcal:280},
  {n:"Patatas fritas bolsa", u:"g", kcal:536},
  {n:"Boniato/batata", u:"g", kcal:86},
  {n:"Yuca", u:"g", kcal:160},
  {n:"Ensalada mezclum bolsa", u:"g", kcal:18},
  {n:"Gazpacho casero", u:"g", kcal:50},
  {n:"Salmorejo casero", u:"g", kcal:120},
  {n:"Pisto", u:"g", kcal:80},
  {n:"Ratatouille", u:"g", kcal:60},
  {n:"Crema de verduras casera", u:"g", kcal:45},
  {n:"Crema calabaza", u:"g", kcal:55},
  {n:"Sopa juliana", u:"g", kcal:25},
  {n:"Caldo verduras", u:"g", kcal:8},
  {n:"Caldo pollo desgrasado", u:"g", kcal:15},
  {n:"Verduras plancha mix", u:"g", kcal:60},
  {n:"Verduras al wok con AOVE", u:"g", kcal:90},

  // ===== CEREALES, PAN Y DERIVADOS (80) =====
  {n:"Pan blanco baguette", u:"g", kcal:265},
  {n:"Pan blanco molde", u:"g", kcal:265},
  {n:"Pan integral molde", u:"g", kcal:247},
  {n:"Pan integral artesano", u:"g", kcal:240},
  {n:"Pan multicereales", u:"g", kcal:250},
  {n:"Pan centeno", u:"g", kcal:259},
  {n:"Pan espelta", u:"g", kcal:255},
  {n:"Pan de semillas Lidl Campeón del Mundo", u:"g", kcal:260},
  {n:"Tostada pan semillas 10mm (~25g)", u:"ud", kcal:65},
  {n:"Pan tostado tipo biscote", u:"g", kcal:390},
  {n:"Biscote integral (~10g)", u:"ud", kcal:38},
  {n:"Pan de hamburguesa", u:"ud", kcal:160},
  {n:"Pan hot dog", u:"ud", kcal:130},
  {n:"Pan pita", u:"ud", kcal:165},
  {n:"Pan naan", u:"ud", kcal:280},
  {n:"Pan ácimo/matzá", u:"g", kcal:370},
  {n:"Picos/regañás", u:"g", kcal:400},
  {n:"Colines/grisines", u:"g", kcal:400},
  {n:"Tortilla maíz mexicana", u:"ud", kcal:65},
  {n:"Tortilla trigo wrap", u:"ud", kcal:140},
  {n:"Arroz blanco crudo", u:"g", kcal:354},
  {n:"Arroz blanco cocido", u:"g", kcal:130},
  {n:"Arroz integral crudo", u:"g", kcal:362},
  {n:"Arroz integral cocido", u:"g", kcal:111},
  {n:"Arroz basmati cocido", u:"g", kcal:121},
  {n:"Arroz salvaje cocido", u:"g", kcal:101},
  {n:"Arroz sushi cocido", u:"g", kcal:130},
  {n:"Pasta seca", u:"g", kcal:371},
  {n:"Pasta cocida", u:"g", kcal:131},
  {n:"Pasta integral cocida", u:"g", kcal:124},
  {n:"Espaguetis cocidos", u:"g", kcal:131},
  {n:"Macarrones cocidos", u:"g", kcal:131},
  {n:"Fideos chinos", u:"g", kcal:138},
  {n:"Fideos arroz", u:"g", kcal:109},
  {n:"Ñoquis", u:"g", kcal:175},
  {n:"Cuscús cocido", u:"g", kcal:112},
  {n:"Bulgur cocido", u:"g", kcal:83},
  {n:"Mijo cocido", u:"g", kcal:119},
  {n:"Quinoa cruda", u:"g", kcal:368},
  {n:"Quinoa cocida", u:"g", kcal:120},
  {n:"Avena copos crudos", u:"g", kcal:389},
  {n:"Avena cocida con agua", u:"g", kcal:71},
  {n:"Salvado avena", u:"g", kcal:246},
  {n:"Salvado trigo", u:"g", kcal:216},
  {n:"Germen de trigo", u:"g", kcal:360},
  {n:"Cereales corn flakes sin azúcar", u:"g", kcal:357},
  {n:"Cereales corn flakes azucarados", u:"g", kcal:380},
  {n:"Cereales All-Bran fibra", u:"g", kcal:334},
  {n:"Cereales chocolate tipo Choco Krispies", u:"g", kcal:387},
  {n:"Cereales muesli sin azúcar", u:"g", kcal:340},
  {n:"Cereales muesli con frutas", u:"g", kcal:370},
  {n:"Granola casera", u:"g", kcal:420},
  {n:"Granola comercial", u:"g", kcal:471},
  {n:"Harina trigo", u:"g", kcal:364},
  {n:"Harina integral", u:"g", kcal:340},
  {n:"Harina maíz", u:"g", kcal:361},
  {n:"Harina avena", u:"g", kcal:404},
  {n:"Harina garbanzo", u:"g", kcal:387},
  {n:"Maicena", u:"g", kcal:381},
  {n:"Polenta cocida", u:"g", kcal:71},
  {n:"Sémola trigo", u:"g", kcal:370},
  {n:"Tortita arroz", u:"ud", kcal:28},
  {n:"Tortita maíz", u:"ud", kcal:25},
  {n:"Galleta María", u:"ud", kcal:23},
  {n:"Galleta integral fibra", u:"ud", kcal:38},
  {n:"Galleta digestive", u:"ud", kcal:71},
  {n:"Galleta tipo Príncipe", u:"ud", kcal:85},
  {n:"Magdalena casera", u:"ud", kcal:160},
  {n:"Croissant mantequilla", u:"ud", kcal:270},
  {n:"Croissant plancha jamón queso", u:"ud", kcal:450},
  {n:"Bizcocho casero", u:"g", kcal:340},
  {n:"Donut glaseado", u:"ud", kcal:250},
  {n:"Palmera chocolate", u:"ud", kcal:380},
  {n:"Napolitana chocolate", u:"ud", kcal:330},
  {n:"Tarta queso", u:"g", kcal:321},
  {n:"Tarta tres chocolates", u:"g", kcal:380},
  {n:"Brownie", u:"g", kcal:466},
  {n:"Muffin chocolate", u:"ud", kcal:380},
  {n:"Empanada gallega atún", u:"g", kcal:230},
  {n:"Empanadilla atún", u:"ud", kcal:160},
  {n:"Pan rallado", u:"g", kcal:395},

  // ===== LÁCTEOS Y DERIVADOS (60) =====
  {n:"Leche entera vaca", u:"g", kcal:61},
  {n:"Leche semidesnatada", u:"g", kcal:46},
  {n:"Leche desnatada", u:"g", kcal:34},
  {n:"Leche sin lactosa entera", u:"g", kcal:61},
  {n:"Leche sin lactosa desnatada", u:"g", kcal:34},
  {n:"Leche cabra", u:"g", kcal:69},
  {n:"Leche oveja", u:"g", kcal:108},
  {n:"Leche condensada", u:"g", kcal:321},
  {n:"Leche evaporada", u:"g", kcal:135},
  {n:"Nata 35% MG", u:"g", kcal:345},
  {n:"Nata cocinar 18% MG", u:"g", kcal:185},
  {n:"Nata ligera 12% MG", u:"g", kcal:130},
  {n:"Crema agria", u:"g", kcal:198},
  {n:"Yogur natural entero", u:"g", kcal:59},
  {n:"Yogur natural desnatado", u:"g", kcal:43},
  {n:"Yogur natural azucarado", u:"g", kcal:90},
  {n:"Yogur sabores entero", u:"g", kcal:97},
  {n:"Yogur sabores desnatado", u:"g", kcal:55},
  {n:"Yogur griego natural", u:"g", kcal:97},
  {n:"Yogur griego 0%", u:"g", kcal:59},
  {n:"Yogur skyr natural", u:"g", kcal:60},
  {n:"Yogur kefir", u:"g", kcal:55},
  {n:"Yogur líquido bebible", u:"g", kcal:75},
  {n:"Yogur Activia natural", u:"g", kcal:55},
  {n:"Petit suisse natural", u:"g", kcal:120},
  {n:"Queso fresco batido 0%", u:"g", kcal:50},
  {n:"Queso fresco batido natural", u:"g", kcal:80},
  {n:"Queso fresco tipo Burgos", u:"g", kcal:174},
  {n:"Queso fresco light", u:"g", kcal:110},
  {n:"Requesón vaca", u:"g", kcal:97},
  {n:"Ricotta", u:"g", kcal:174},
  {n:"Mascarpone", u:"g", kcal:429},
  {n:"Mozzarella", u:"g", kcal:280},
  {n:"Mozzarella light", u:"g", kcal:191},
  {n:"Mozzarella búfala", u:"g", kcal:288},
  {n:"Burrata", u:"g", kcal:330},
  {n:"Queso curado oveja", u:"g", kcal:411},
  {n:"Queso semicurado", u:"g", kcal:370},
  {n:"Queso tierno", u:"g", kcal:325},
  {n:"Manchego curado", u:"g", kcal:476},
  {n:"Queso cabra rulo", u:"g", kcal:364},
  {n:"Queso azul cabrales", u:"g", kcal:353},
  {n:"Roquefort", u:"g", kcal:369},
  {n:"Gorgonzola", u:"g", kcal:330},
  {n:"Brie", u:"g", kcal:334},
  {n:"Camembert", u:"g", kcal:300},
  {n:"Emmental", u:"g", kcal:380},
  {n:"Gruyère", u:"g", kcal:413},
  {n:"Cheddar", u:"g", kcal:402},
  {n:"Parmesano", u:"g", kcal:431},
  {n:"Queso lonchas tranchete", u:"ud", kcal:60},
  {n:"Queso quesitos porción", u:"ud", kcal:55},
  {n:"Queso crema tipo Philadelphia", u:"g", kcal:253},
  {n:"Queso crema light", u:"g", kcal:145},
  {n:"Mantequilla", u:"g", kcal:717},
  {n:"Mantequilla light", u:"g", kcal:520},
  {n:"Margarina vegetal", u:"g", kcal:626},
  {n:"Helado vainilla", u:"g", kcal:207},
  {n:"Helado chocolate", u:"g", kcal:216},
  {n:"Helado yogur", u:"g", kcal:170},

  // ===== CARNES (80) =====
  {n:"Pechuga pollo cruda", u:"g", kcal:107},
  {n:"Pechuga pollo plancha", u:"g", kcal:165},
  {n:"Pechuga pollo asada", u:"g", kcal:165},
  {n:"Pechuga pollo empanada", u:"g", kcal:260},
  {n:"Muslo pollo con piel", u:"g", kcal:209},
  {n:"Muslo pollo sin piel", u:"g", kcal:170},
  {n:"Contramuslo pollo sin piel", u:"g", kcal:177},
  {n:"Alitas pollo", u:"g", kcal:203},
  {n:"Pollo asado entero con piel", u:"g", kcal:240},
  {n:"Higadillos pollo", u:"g", kcal:119},
  {n:"Pechuga pavo cruda", u:"g", kcal:120},
  {n:"Pechuga pavo plancha", u:"g", kcal:135},
  {n:"Muslo pavo", u:"g", kcal:144},
  {n:"Codorniz", u:"g", kcal:227},
  {n:"Conejo", u:"g", kcal:173},
  {n:"Pato pechuga", u:"g", kcal:201},
  {n:"Pato magret", u:"g", kcal:337},
  {n:"Ternera solomillo", u:"g", kcal:158},
  {n:"Ternera lomo bajo", u:"g", kcal:215},
  {n:"Ternera entrecot", u:"g", kcal:271},
  {n:"Ternera filete cadera", u:"g", kcal:131},
  {n:"Ternera redondo", u:"g", kcal:131},
  {n:"Ternera tapa", u:"g", kcal:131},
  {n:"Ternera babilla", u:"g", kcal:131},
  {n:"Ternera carne picada 5% grasa", u:"g", kcal:137},
  {n:"Ternera carne picada 10% grasa", u:"g", kcal:184},
  {n:"Ternera carne picada 20% grasa", u:"g", kcal:254},
  {n:"Vaca chuletón", u:"g", kcal:280},
  {n:"Vaca rabo guisado", u:"g", kcal:240},
  {n:"Buey solomillo", u:"g", kcal:170},
  {n:"Hamburguesa ternera 100g", u:"ud", kcal:240},
  {n:"Cerdo lomo crudo", u:"g", kcal:143},
  {n:"Cerdo lomo plancha", u:"g", kcal:200},
  {n:"Cerdo solomillo", u:"g", kcal:134},
  {n:"Cerdo costilla", u:"g", kcal:277},
  {n:"Cerdo panceta", u:"g", kcal:518},
  {n:"Cerdo secreto ibérico", u:"g", kcal:300},
  {n:"Cerdo presa ibérica", u:"g", kcal:250},
  {n:"Cerdo pluma ibérica", u:"g", kcal:240},
  {n:"Cerdo carrillera guisada", u:"g", kcal:280},
  {n:"Cerdo cochinillo", u:"g", kcal:350},
  {n:"Bacon ahumado", u:"g", kcal:541},
  {n:"Panceta ibérica curada", u:"g", kcal:541},
  {n:"Tocino", u:"g", kcal:891},
  {n:"Cordero pierna", u:"g", kcal:235},
  {n:"Cordero chuleta", u:"g", kcal:290},
  {n:"Cordero costillar", u:"g", kcal:360},
  {n:"Cabrito", u:"g", kcal:165},
  {n:"Caballo carne", u:"g", kcal:110},
  {n:"Caza ciervo", u:"g", kcal:120},
  {n:"Caza jabalí", u:"g", kcal:122},
  {n:"Caza perdiz", u:"g", kcal:120},
  {n:"Jamón serrano", u:"g", kcal:241},
  {n:"Jamón ibérico bellota", u:"g", kcal:375},
  {n:"Jamón ibérico cebo", u:"g", kcal:340},
  {n:"Jamón cocido extra", u:"g", kcal:108},
  {n:"Jamón cocido bajo en sal", u:"g", kcal:103},
  {n:"Pavo cocido fiambre", u:"g", kcal:110},
  {n:"Pollo cocido fiambre", u:"g", kcal:115},
  {n:"Lomo embuchado", u:"g", kcal:230},
  {n:"Cecina León", u:"g", kcal:243},
  {n:"Chorizo curado", u:"g", kcal:455},
  {n:"Chorizo ibérico", u:"g", kcal:480},
  {n:"Chorizo cular fresco", u:"g", kcal:300},
  {n:"Salchichón curado", u:"g", kcal:455},
  {n:"Fuet", u:"g", kcal:445},
  {n:"Sobrasada", u:"g", kcal:530},
  {n:"Salchicha Frankfurt", u:"g", kcal:248},
  {n:"Salchicha Bratwurst", u:"g", kcal:300},
  {n:"Morcilla arroz", u:"g", kcal:380},
  {n:"Morcilla cebolla", u:"g", kcal:300},
  {n:"Butifarra blanca", u:"g", kcal:330},
  {n:"Botillo bercianno", u:"g", kcal:300},
  {n:"Mortadela", u:"g", kcal:311},
  {n:"Salami", u:"g", kcal:336},
  {n:"Foie gras", u:"g", kcal:462},
  {n:"Paté hígado cerdo", u:"g", kcal:319},
  {n:"Sobrasada mallorquina", u:"g", kcal:530},
  {n:"Albóndigas casera ternera", u:"g", kcal:200},
  {n:"Salchichón vela tradicional", u:"g", kcal:432},
  {n:"Lacón cocido", u:"g", kcal:170},

  // ===== PESCADOS Y MARISCOS (80) =====
  {n:"Merluza fresca", u:"g", kcal:71},
  {n:"Merluza congelada", u:"g", kcal:71},
  {n:"Pescadilla", u:"g", kcal:75},
  {n:"Bacalao fresco", u:"g", kcal:82},
  {n:"Bacalao salado desalado", u:"g", kcal:131},
  {n:"Bacalao ahumado", u:"g", kcal:120},
  {n:"Lubina", u:"g", kcal:97},
  {n:"Dorada", u:"g", kcal:97},
  {n:"Rape", u:"g", kcal:68},
  {n:"Lenguado", u:"g", kcal:73},
  {n:"Gallo san Pedro", u:"g", kcal:75},
  {n:"Rodaballo", u:"g", kcal:81},
  {n:"Mero", u:"g", kcal:80},
  {n:"Cabracho", u:"g", kcal:97},
  {n:"Salmón fresco", u:"g", kcal:208},
  {n:"Salmón ahumado", u:"g", kcal:185},
  {n:"Salmón a la plancha", u:"g", kcal:230},
  {n:"Trucha", u:"g", kcal:148},
  {n:"Trucha ahumada", u:"g", kcal:170},
  {n:"Atún fresco", u:"g", kcal:144},
  {n:"Atún rojo", u:"g", kcal:184},
  {n:"Atún en aceite oliva", u:"g", kcal:189},
  {n:"Atún en aceite girasol", u:"g", kcal:200},
  {n:"Atún al natural escurrido", u:"g", kcal:108},
  {n:"Bonito del norte aceite", u:"g", kcal:225},
  {n:"Bonito del norte natural", u:"g", kcal:130},
  {n:"Caballa fresca", u:"g", kcal:205},
  {n:"Caballa en aceite", u:"g", kcal:262},
  {n:"Sardinas frescas", u:"g", kcal:208},
  {n:"Sardinas en aceite", u:"g", kcal:208},
  {n:"Sardinas en escabeche", u:"g", kcal:190},
  {n:"Boquerones frescos", u:"g", kcal:131},
  {n:"Boquerones en vinagre", u:"g", kcal:175},
  {n:"Anchoa en aceite", u:"g", kcal:210},
  {n:"Arenque", u:"g", kcal:158},
  {n:"Arenque ahumado", u:"g", kcal:215},
  {n:"Verdel", u:"g", kcal:200},
  {n:"Jurel", u:"g", kcal:140},
  {n:"Pez espada", u:"g", kcal:121},
  {n:"Emperador", u:"g", kcal:121},
  {n:"Salmonete", u:"g", kcal:123},
  {n:"Pargo", u:"g", kcal:100},
  {n:"Besugo", u:"g", kcal:118},
  {n:"Rape al horno", u:"g", kcal:90},
  {n:"Palometa", u:"g", kcal:140},
  {n:"Palitos cangrejo surimi", u:"g", kcal:99},
  {n:"Gambas peladas crudas", u:"g", kcal:71},
  {n:"Gambas cocidas", u:"g", kcal:99},
  {n:"Langostinos crudos", u:"g", kcal:96},
  {n:"Langostinos cocidos", u:"g", kcal:106},
  {n:"Cigalas", u:"g", kcal:91},
  {n:"Langosta", u:"g", kcal:89},
  {n:"Bogavante", u:"g", kcal:90},
  {n:"Centollo", u:"g", kcal:90},
  {n:"Buey de mar", u:"g", kcal:85},
  {n:"Nécora", u:"g", kcal:80},
  {n:"Cangrejo de río", u:"g", kcal:73},
  {n:"Calamares frescos", u:"g", kcal:82},
  {n:"Calamares plancha", u:"g", kcal:100},
  {n:"Calamares romana fritos", u:"g", kcal:175},
  {n:"Calamares en su tinta", u:"g", kcal:120},
  {n:"Chipirones", u:"g", kcal:82},
  {n:"Sepia", u:"g", kcal:79},
  {n:"Pulpo fresco", u:"g", kcal:82},
  {n:"Pulpo a la gallega", u:"g", kcal:140},
  {n:"Mejillones frescos", u:"g", kcal:74},
  {n:"Mejillones en escabeche", u:"g", kcal:172},
  {n:"Mejillones al natural lata", u:"g", kcal:80},
  {n:"Almejas", u:"g", kcal:76},
  {n:"Berberechos frescos", u:"g", kcal:81},
  {n:"Berberechos al natural lata", u:"g", kcal:75},
  {n:"Navajas", u:"g", kcal:80},
  {n:"Vieiras", u:"g", kcal:88},
  {n:"Zamburiñas", u:"g", kcal:80},
  {n:"Ostras", u:"g", kcal:81},
  {n:"Caviar", u:"g", kcal:264},
  {n:"Huevas pescado", u:"g", kcal:160},
  {n:"Surimi", u:"g", kcal:99},
  {n:"Empanada bonito", u:"g", kcal:230},
  {n:"Empanada zamburiñas", u:"g", kcal:235},
  {n:"Croqueta bacalao", u:"ud", kcal:75},

  // ===== HUEVOS (10) =====
  {n:"Huevo entero gallina M (~55g)", u:"ud", kcal:78},
  {n:"Huevo entero gallina L (~63g)", u:"ud", kcal:90},
  {n:"Huevo entero gallina XL (~73g)", u:"ud", kcal:104},
  {n:"Clara de huevo", u:"g", kcal:52},
  {n:"Yema de huevo", u:"g", kcal:322},
  {n:"Huevo cocido", u:"ud", kcal:78},
  {n:"Huevo frito con aceite", u:"ud", kcal:130},
  {n:"Huevo poché", u:"ud", kcal:78},
  {n:"Tortilla francesa 2 huevos AOVE", u:"ud", kcal:200},
  {n:"Huevo codorniz", u:"ud", kcal:14},

  // ===== LEGUMBRES (40) =====
  {n:"Lentejas crudas", u:"g", kcal:336},
  {n:"Lentejas pardinas cocidas", u:"g", kcal:116},
  {n:"Lentejas castellanas cocidas", u:"g", kcal:116},
  {n:"Lentejas rojas cocidas", u:"g", kcal:120},
  {n:"Lentejas beluga cocidas", u:"g", kcal:130},
  {n:"Lentejas con chorizo", u:"g", kcal:160},
  {n:"Garbanzos crudos", u:"g", kcal:364},
  {n:"Garbanzos cocidos", u:"g", kcal:164},
  {n:"Garbanzos en bote conserva", u:"g", kcal:120},
  {n:"Garbanzos tostados", u:"g", kcal:380},
  {n:"Hummus tradicional", u:"g", kcal:166},
  {n:"Falafel", u:"g", kcal:333},
  {n:"Alubia blanca cruda", u:"g", kcal:333},
  {n:"Alubia blanca cocida", u:"g", kcal:127},
  {n:"Alubia roja cruda", u:"g", kcal:333},
  {n:"Alubia roja cocida", u:"g", kcal:127},
  {n:"Alubia pinta cocida", u:"g", kcal:143},
  {n:"Alubia negra cocida", u:"g", kcal:132},
  {n:"Fabada asturiana", u:"g", kcal:180},
  {n:"Frijoles refritos", u:"g", kcal:91},
  {n:"Judión Granja cocido", u:"g", kcal:130},
  {n:"Habas secas crudas", u:"g", kcal:341},
  {n:"Habas secas cocidas", u:"g", kcal:110},
  {n:"Soja seca", u:"g", kcal:446},
  {n:"Soja cocida", u:"g", kcal:173},
  {n:"Soja texturizada seca", u:"g", kcal:340},
  {n:"Soja texturizada hidratada", u:"g", kcal:110},
  {n:"Tofu firme", u:"g", kcal:144},
  {n:"Tofu sedoso", u:"g", kcal:55},
  {n:"Tempeh", u:"g", kcal:193},
  {n:"Seitán", u:"g", kcal:120},
  {n:"Heura tipo pollo", u:"g", kcal:108},
  {n:"Hamburguesa vegetal soja", u:"ud", kcal:170},
  {n:"Cacahuetes tostados", u:"g", kcal:585},
  {n:"Crema de cacahuete 100%", u:"g", kcal:588},
  {n:"Mantequilla cacahuete azucarada", u:"g", kcal:620},
  {n:"Garbanzos potaje espinacas bacalao", u:"g", kcal:140},
  {n:"Lentejas verdes cocidas", u:"g", kcal:116},
  {n:"Lentejas con verduras", u:"g", kcal:110},
  {n:"Sopa lentejas", u:"g", kcal:70},

  // ===== FRUTOS SECOS Y SEMILLAS (40) =====
  {n:"Almendra cruda", u:"g", kcal:579},
  {n:"Almendra tostada sin sal", u:"g", kcal:597},
  {n:"Almendra frita salada", u:"g", kcal:625},
  {n:"Almendra Marcona", u:"g", kcal:600},
  {n:"Crema de almendra", u:"g", kcal:614},
  {n:"Harina almendra", u:"g", kcal:597},
  {n:"Nuez común", u:"g", kcal:654},
  {n:"Nuez California", u:"g", kcal:654},
  {n:"Nuez de Brasil", u:"g", kcal:659},
  {n:"Nuez pecana", u:"g", kcal:691},
  {n:"Nuez macadamia", u:"g", kcal:718},
  {n:"Avellana cruda", u:"g", kcal:628},
  {n:"Avellana tostada", u:"g", kcal:646},
  {n:"Crema avellana cacao tipo Nutella", u:"g", kcal:539},
  {n:"Crema avellana 100%", u:"g", kcal:646},
  {n:"Pistacho con cáscara", u:"g", kcal:280},
  {n:"Pistacho pelado", u:"g", kcal:560},
  {n:"Cacahuete crudo", u:"g", kcal:567},
  {n:"Cacahuete tostado salado", u:"g", kcal:585},
  {n:"Cacahuete frito", u:"g", kcal:620},
  {n:"Anacardo crudo", u:"g", kcal:553},
  {n:"Anacardo tostado", u:"g", kcal:574},
  {n:"Piñón", u:"g", kcal:673},
  {n:"Castaña cruda", u:"g", kcal:213},
  {n:"Castaña asada", u:"g", kcal:245},
  {n:"Pipas girasol con cáscara", u:"g", kcal:300},
  {n:"Pipas girasol peladas", u:"g", kcal:584},
  {n:"Pipas calabaza", u:"g", kcal:559},
  {n:"Semillas chía", u:"g", kcal:486},
  {n:"Semillas lino", u:"g", kcal:534},
  {n:"Semillas sésamo", u:"g", kcal:573},
  {n:"Semillas amapola", u:"g", kcal:525},
  {n:"Tahini sésamo", u:"g", kcal:595},
  {n:"Mezcla frutos secos sin sal", u:"g", kcal:600},
  {n:"Mezcla frutos secos con pasas", u:"g", kcal:480},
  {n:"Barrita frutos secos", u:"ud", kcal:130},
  {n:"Coco rallado", u:"g", kcal:660},
  {n:"Leche coco", u:"g", kcal:230},
  {n:"Bebida coco light", u:"g", kcal:30},
  {n:"Granola frutos secos", u:"g", kcal:471},

  // ===== ACEITES Y GRASAS (20) =====
  {n:"Aceite oliva virgen extra (AOVE)", u:"g", kcal:884},
  {n:"Aceite oliva virgen", u:"g", kcal:884},
  {n:"Aceite oliva refinado", u:"g", kcal:884},
  {n:"Aceite girasol", u:"g", kcal:884},
  {n:"Aceite girasol alto oleico", u:"g", kcal:884},
  {n:"Aceite maíz", u:"g", kcal:884},
  {n:"Aceite soja", u:"g", kcal:884},
  {n:"Aceite coco", u:"g", kcal:892},
  {n:"Aceite aguacate", u:"g", kcal:884},
  {n:"Aceite sésamo", u:"g", kcal:884},
  {n:"Aceite lino", u:"g", kcal:884},
  {n:"Manteca cerdo", u:"g", kcal:891},
  {n:"Manteca vaca", u:"g", kcal:876},
  {n:"Mayonesa casera", u:"g", kcal:680},
  {n:"Mayonesa comercial", u:"g", kcal:680},
  {n:"Mayonesa light", u:"g", kcal:240},
  {n:"Alioli", u:"g", kcal:706},
  {n:"Vinagreta AOVE", u:"g", kcal:450},
  {n:"Ketchup", u:"g", kcal:103},
  {n:"Mostaza", u:"g", kcal:66},

  // ===== AZÚCARES Y DULCES (50) =====
  {n:"Azúcar blanco", u:"g", kcal:387},
  {n:"Azúcar moreno", u:"g", kcal:380},
  {n:"Azúcar glas", u:"g", kcal:389},
  {n:"Sacarina/edulcorante artificial", u:"g", kcal:0},
  {n:"Stevia", u:"g", kcal:0},
  {n:"Eritritol", u:"g", kcal:0},
  {n:"Sirope agave", u:"g", kcal:310},
  {n:"Sirope arce", u:"g", kcal:260},
  {n:"Miel", u:"g", kcal:304},
  {n:"Melaza caña", u:"g", kcal:290},
  {n:"Mermelada azúcar", u:"g", kcal:278},
  {n:"Mermelada sin azúcar", u:"g", kcal:120},
  {n:"Confitura fresa", u:"g", kcal:248},
  {n:"Crema cacao avellanas", u:"g", kcal:539},
  {n:"Chocolate negro 50%", u:"g", kcal:550},
  {n:"Chocolate negro 70%", u:"g", kcal:546},
  {n:"Chocolate negro 85%", u:"g", kcal:600},
  {n:"Chocolate negro 99%", u:"g", kcal:620},
  {n:"Chocolate con leche", u:"g", kcal:535},
  {n:"Chocolate blanco", u:"g", kcal:539},
  {n:"Bombón mediano", u:"ud", kcal:55},
  {n:"Onza chocolate (~5g)", u:"ud", kcal:27},
  {n:"Caramelo duro", u:"ud", kcal:20},
  {n:"Caramelo blando", u:"ud", kcal:25},
  {n:"Chicle azucarado", u:"ud", kcal:8},
  {n:"Chicle sin azúcar", u:"ud", kcal:3},
  {n:"Gominola/regaliz", u:"g", kcal:340},
  {n:"Turrón duro Alicante", u:"g", kcal:520},
  {n:"Turrón blando Jijona", u:"g", kcal:580},
  {n:"Turrón chocolate", u:"g", kcal:540},
  {n:"Mazapán", u:"g", kcal:480},
  {n:"Mantecado", u:"ud", kcal:80},
  {n:"Polvorón", u:"ud", kcal:90},
  {n:"Roscón Reyes nata", u:"g", kcal:370},
  {n:"Torrija casera", u:"ud", kcal:280},
  {n:"Crema catalana", u:"g", kcal:200},
  {n:"Flan huevo", u:"ud", kcal:140},
  {n:"Natillas caseras", u:"g", kcal:140},
  {n:"Arroz con leche", u:"g", kcal:150},
  {n:"Mousse chocolate", u:"g", kcal:225},
  {n:"Tiramisú", u:"g", kcal:280},
  {n:"Cheesecake", u:"g", kcal:321},
  {n:"Profiterol", u:"ud", kcal:120},
  {n:"Helado nata cono", u:"ud", kcal:220},
  {n:"Helado magnum clásico", u:"ud", kcal:260},
  {n:"Calippo limón", u:"ud", kcal:100},
  {n:"Polo agua sabor frutas", u:"ud", kcal:60},
  {n:"Sorbete frutas", u:"g", kcal:130},
  {n:"Algodón azúcar", u:"g", kcal:380},
  {n:"Crocante almendra", u:"g", kcal:480},

  // ===== BEBIDAS NO ALCOHÓLICAS (50) =====
  {n:"Agua", u:"g", kcal:0},
  {n:"Agua con gas", u:"g", kcal:0},
  {n:"Café solo expresso (sin azúcar)", u:"ud", kcal:2},
  {n:"Café americano (sin azúcar)", u:"ud", kcal:5},
  {n:"Café con leche desnatada 200ml (60ml leche)", u:"ud", kcal:24},
  {n:"Café con leche semidesnatada 200ml", u:"ud", kcal:32},
  {n:"Café con leche entera 200ml", u:"ud", kcal:40},
  {n:"Café cortado (con leche desnatada)", u:"ud", kcal:12},
  {n:"Café latte (200ml leche entera)", u:"ud", kcal:130},
  {n:"Capuccino (150ml leche entera)", u:"ud", kcal:90},
  {n:"Café descafeinado solo", u:"ud", kcal:2},
  {n:"Té verde sin azúcar", u:"ud", kcal:2},
  {n:"Té negro sin azúcar", u:"ud", kcal:2},
  {n:"Té rojo Pu-erh", u:"ud", kcal:2},
  {n:"Té rooibos", u:"ud", kcal:2},
  {n:"Té chai con leche desnatada", u:"ud", kcal:60},
  {n:"Infusión manzanilla", u:"ud", kcal:2},
  {n:"Infusión tila", u:"ud", kcal:2},
  {n:"Infusión menta poleo", u:"ud", kcal:2},
  {n:"Mate cocido", u:"ud", kcal:5},
  {n:"Cacao en polvo sin azúcar", u:"g", kcal:228},
  {n:"Cacao Cola Cao", u:"g", kcal:380},
  {n:"Chocolate caliente con leche", u:"g", kcal:90},
  {n:"Zumo naranja natural", u:"g", kcal:45},
  {n:"Zumo naranja envasado", u:"g", kcal:46},
  {n:"Zumo manzana envasado", u:"g", kcal:46},
  {n:"Zumo piña envasado", u:"g", kcal:50},
  {n:"Zumo melocotón", u:"g", kcal:48},
  {n:"Zumo multifrutas", u:"g", kcal:50},
  {n:"Néctar fruta", u:"g", kcal:55},
  {n:"Refresco cola", u:"g", kcal:42},
  {n:"Refresco cola zero", u:"g", kcal:0},
  {n:"Refresco naranja", u:"g", kcal:42},
  {n:"Refresco limón", u:"g", kcal:40},
  {n:"Tónica", u:"g", kcal:38},
  {n:"Tónica light", u:"g", kcal:2},
  {n:"Bitter Kas", u:"g", kcal:35},
  {n:"Bebida energética Red Bull", u:"g", kcal:45},
  {n:"Bebida energética sin azúcar", u:"g", kcal:3},
  {n:"Bebida isotónica Aquarius", u:"g", kcal:24},
  {n:"Bebida isotónica Powerade", u:"g", kcal:25},
  {n:"Horchata", u:"g", kcal:100},
  {n:"Granizado limón", u:"g", kcal:90},
  {n:"Batido fresa", u:"g", kcal:80},
  {n:"Batido chocolate", u:"g", kcal:84},
  {n:"Bebida soja sin azúcar", u:"g", kcal:33},
  {n:"Bebida soja vainilla", u:"g", kcal:54},
  {n:"Bebida almendra sin azúcar", u:"g", kcal:13},
  {n:"Bebida avena", u:"g", kcal:45},
  {n:"Bebida arroz", u:"g", kcal:47},

  // ===== BEBIDAS ALCOHÓLICAS (30) =====
  {n:"Cerveza rubia 5%", u:"g", kcal:43},
  {n:"Cerveza negra", u:"g", kcal:50},
  {n:"Cerveza sin alcohol", u:"g", kcal:24},
  {n:"Cerveza 0,0", u:"g", kcal:17},
  {n:"Cerveza tostada", u:"g", kcal:47},
  {n:"Caña cerveza (~200ml)", u:"ud", kcal:86},
  {n:"Tercio cerveza (~330ml)", u:"ud", kcal:142},
  {n:"Pinta cerveza (~500ml)", u:"ud", kcal:215},
  {n:"Vino tinto", u:"g", kcal:85},
  {n:"Vino blanco seco", u:"g", kcal:82},
  {n:"Vino blanco semidulce", u:"g", kcal:90},
  {n:"Vino rosado", u:"g", kcal:83},
  {n:"Cava brut", u:"g", kcal:78},
  {n:"Champán", u:"g", kcal:78},
  {n:"Vermut blanco", u:"g", kcal:142},
  {n:"Vermut rojo", u:"g", kcal:145},
  {n:"Jerez fino", u:"g", kcal:114},
  {n:"Jerez oloroso", u:"g", kcal:140},
  {n:"Oporto", u:"g", kcal:155},
  {n:"Whisky", u:"g", kcal:250},
  {n:"Ron", u:"g", kcal:230},
  {n:"Vodka", u:"g", kcal:235},
  {n:"Ginebra", u:"g", kcal:230},
  {n:"Tequila", u:"g", kcal:230},
  {n:"Brandy", u:"g", kcal:225},
  {n:"Coñac", u:"g", kcal:240},
  {n:"Licor café orujo", u:"g", kcal:330},
  {n:"Pacharán", u:"g", kcal:290},
  {n:"Sidra natural", u:"g", kcal:33},
  {n:"Mojito (vaso)", u:"ud", kcal:215},

  // ===== PRECOCINADOS, COMIDA RÁPIDA Y SNACKS (60) =====
  {n:"Pizza margarita", u:"g", kcal:266},
  {n:"Pizza 4 quesos", u:"g", kcal:305},
  {n:"Pizza pepperoni", u:"g", kcal:298},
  {n:"Pizza barbacoa", u:"g", kcal:285},
  {n:"Pizza jamón y queso", u:"g", kcal:280},
  {n:"Lasaña carne", u:"g", kcal:135},
  {n:"Canelones carne", u:"g", kcal:145},
  {n:"Espaguetis boloñesa", u:"g", kcal:155},
  {n:"Espaguetis carbonara", u:"g", kcal:200},
  {n:"Paella valenciana", u:"g", kcal:150},
  {n:"Paella marisco", u:"g", kcal:155},
  {n:"Arroz a la cubana", u:"g", kcal:200},
  {n:"Arroz con pollo", u:"g", kcal:170},
  {n:"Risotto setas", u:"g", kcal:165},
  {n:"Macarrones boloñesa", u:"g", kcal:165},
  {n:"Tortilla patata", u:"g", kcal:200},
  {n:"Tortilla francesa simple", u:"g", kcal:175},
  {n:"Croqueta jamón", u:"ud", kcal:75},
  {n:"Croqueta pollo", u:"ud", kcal:70},
  {n:"Croqueta bacalao", u:"ud", kcal:70},
  {n:"Empanadilla atún", u:"ud", kcal:160},
  {n:"Empanada gallega", u:"g", kcal:230},
  {n:"Quiche lorraine", u:"g", kcal:300},
  {n:"Hamburguesa Big Mac", u:"ud", kcal:540},
  {n:"Hamburguesa Whopper", u:"ud", kcal:660},
  {n:"Hamburguesa Quarter Pounder", u:"ud", kcal:520},
  {n:"Patatas fritas McDonalds medianas", u:"ud", kcal:340},
  {n:"Patatas fritas McDonalds grandes", u:"ud", kcal:490},
  {n:"Nuggets pollo (6 ud)", u:"ud", kcal:280},
  {n:"Kebab pollo", u:"ud", kcal:520},
  {n:"Kebab ternera con salsa", u:"ud", kcal:650},
  {n:"Durum pollo", u:"ud", kcal:580},
  {n:"Burrito carne", u:"ud", kcal:520},
  {n:"Taco carne", u:"ud", kcal:220},
  {n:"Quesadilla queso", u:"ud", kcal:300},
  {n:"Fajita pollo", u:"ud", kcal:340},
  {n:"Sushi maki (8 piezas)", u:"ud", kcal:300},
  {n:"Nigiri salmón (1 pieza)", u:"ud", kcal:45},
  {n:"Temaki", u:"ud", kcal:140},
  {n:"Pollo agridulce chino", u:"g", kcal:240},
  {n:"Rollito primavera", u:"ud", kcal:160},
  {n:"Arroz tres delicias", u:"g", kcal:180},
  {n:"Noodles wok pollo", u:"g", kcal:150},
  {n:"Pad thai", u:"g", kcal:210},
  {n:"Curry pollo tikka masala", u:"g", kcal:155},
  {n:"Cuscús cordero", u:"g", kcal:160},
  {n:"Patatas chips bolsa", u:"g", kcal:536},
  {n:"Patatas chips horneadas", u:"g", kcal:430},
  {n:"Doritos", u:"g", kcal:498},
  {n:"Cheetos", u:"g", kcal:550},
  {n:"Palomitas microondas", u:"g", kcal:430},
  {n:"Palomitas caseras aceite", u:"g", kcal:480},
  {n:"Palomitas saladas cine", u:"g", kcal:500},
  {n:"Palomitas dulces", u:"g", kcal:430},
  {n:"Pretzel salado", u:"g", kcal:380},
  {n:"Galletas saladas crackers", u:"g", kcal:425},
  {n:"Picos andaluces", u:"g", kcal:400},
  {n:"Kikos maíz frito", u:"g", kcal:430},
  {n:"Pipas saladas pelar", u:"g", kcal:584},
  {n:"Barrita cereales chocolate", u:"ud", kcal:120},

  // ===== SALSAS Y CONDIMENTOS (40) =====
  {n:"Sal", u:"g", kcal:0},
  {n:"Pimienta negra molida", u:"g", kcal:251},
  {n:"Vinagre vino", u:"g", kcal:19},
  {n:"Vinagre Módena", u:"g", kcal:88},
  {n:"Vinagre manzana", u:"g", kcal:22},
  {n:"Salsa soja", u:"g", kcal:53},
  {n:"Salsa teriyaki", u:"g", kcal:89},
  {n:"Salsa Worcestershire", u:"g", kcal:78},
  {n:"Salsa barbacoa", u:"g", kcal:170},
  {n:"Salsa bechamel", u:"g", kcal:130},
  {n:"Salsa carbonara comercial", u:"g", kcal:250},
  {n:"Salsa boloñesa comercial", u:"g", kcal:85},
  {n:"Salsa tomate frito comercial", u:"g", kcal:80},
  {n:"Salsa pesto verde", u:"g", kcal:430},
  {n:"Salsa pesto rojo", u:"g", kcal:280},
  {n:"Salsa rosa", u:"g", kcal:430},
  {n:"Tártara", u:"g", kcal:485},
  {n:"Salsa César", u:"g", kcal:430},
  {n:"Salsa yogur pepino", u:"g", kcal:60},
  {n:"Mostaza Dijon", u:"g", kcal:78},
  {n:"Mostaza antigua", u:"g", kcal:140},
  {n:"Wasabi", u:"g", kcal:110},
  {n:"Salsa picante Tabasco", u:"g", kcal:12},
  {n:"Salsa Sriracha", u:"g", kcal:95},
  {n:"Ajilimójili", u:"g", kcal:120},
  {n:"Mojo picón", u:"g", kcal:200},
  {n:"Salsa romesco", u:"g", kcal:200},
  {n:"Chimichurri", u:"g", kcal:340},
  {n:"Guacamole", u:"g", kcal:160},
  {n:"Hummus comercial", u:"g", kcal:166},
  {n:"Babaganoush", u:"g", kcal:150},
  {n:"Pesto rojo casero", u:"g", kcal:330},
  {n:"Levadura nutricional", u:"g", kcal:325},
  {n:"Levadura panadero seca", u:"g", kcal:320},
  {n:"Bicarbonato sódico", u:"g", kcal:0},
  {n:"Pimentón dulce", u:"g", kcal:282},
  {n:"Pimentón picante", u:"g", kcal:282},
  {n:"Curry en polvo", u:"g", kcal:325},
  {n:"Comino molido", u:"g", kcal:375},
  {n:"Orégano seco", u:"g", kcal:265},

  // ===== ESPECIAS Y HIERBAS (30) =====
  {n:"Albahaca fresca", u:"g", kcal:23},
  {n:"Albahaca seca", u:"g", kcal:233},
  {n:"Romero seco", u:"g", kcal:331},
  {n:"Tomillo seco", u:"g", kcal:276},
  {n:"Laurel seco", u:"g", kcal:313},
  {n:"Perejil fresco", u:"g", kcal:36},
  {n:"Cilantro fresco", u:"g", kcal:23},
  {n:"Eneldo seco", u:"g", kcal:253},
  {n:"Menta fresca", u:"g", kcal:44},
  {n:"Hierbabuena fresca", u:"g", kcal:44},
  {n:"Cebollino fresco", u:"g", kcal:30},
  {n:"Estragón seco", u:"g", kcal:295},
  {n:"Salvia seca", u:"g", kcal:315},
  {n:"Mejorana seca", u:"g", kcal:271},
  {n:"Canela molida", u:"g", kcal:247},
  {n:"Jengibre molido", u:"g", kcal:335},
  {n:"Cúrcuma molida", u:"g", kcal:354},
  {n:"Clavo molido", u:"g", kcal:274},
  {n:"Nuez moscada", u:"g", kcal:525},
  {n:"Cardamomo", u:"g", kcal:311},
  {n:"Anís verde", u:"g", kcal:337},
  {n:"Hinojo semillas", u:"g", kcal:345},
  {n:"Mostaza semillas", u:"g", kcal:508},
  {n:"Vainilla esencia", u:"g", kcal:288},
  {n:"Azafrán", u:"g", kcal:310},
  {n:"Cayena", u:"g", kcal:318},
  {n:"Cinco especias chinas", u:"g", kcal:300},
  {n:"Ras el hanout", u:"g", kcal:300},
  {n:"Garam masala", u:"g", kcal:320},
  {n:"Mezcla provenzales", u:"g", kcal:280},

  // ===== SUPLEMENTOS Y ESPECIALES (20) =====
  {n:"Proteína whey en polvo", u:"g", kcal:390},
  {n:"Proteína caseína", u:"g", kcal:380},
  {n:"Proteína vegana guisante", u:"g", kcal:370},
  {n:"Batido proteína whey (30g)", u:"ud", kcal:117},
  {n:"Barrita proteína", u:"ud", kcal:200},
  {n:"Creatina monohidrato", u:"g", kcal:0},
  {n:"BCAA polvo", u:"g", kcal:0},
  {n:"Glutamina polvo", u:"g", kcal:0},
  {n:"Aceite MCT", u:"g", kcal:820},
  {n:"Ghee", u:"g", kcal:900},
  {n:"Kombucha", u:"g", kcal:25},
  {n:"Kéfir agua", u:"g", kcal:25},
  {n:"Vinagre manzana sin filtrar", u:"g", kcal:22},
  {n:"Espirulina polvo", u:"g", kcal:290},
  {n:"Chlorella polvo", u:"g", kcal:410},
  {n:"Maca polvo", u:"g", kcal:325},
  {n:"Levadura cerveza", u:"g", kcal:295},
  {n:"Polen abeja", u:"g", kcal:340},
  {n:"Jalea real", u:"g", kcal:330},
  {n:"Propóleo", u:"g", kcal:300},

  // ===== AMPLIACIÓN: comidas/platos típicos españoles y caseros (60) =====
  {n:"Cocido madrileño (ración)", u:"g", kcal:200},
  {n:"Cocido maragato", u:"g", kcal:210},
  {n:"Pote gallego", u:"g", kcal:160},
  {n:"Caldo gallego", u:"g", kcal:80},
  {n:"Caldeirada pescado", u:"g", kcal:110},
  {n:"Lacón con grelos", u:"g", kcal:180},
  {n:"Pulpo a feira", u:"g", kcal:160},
  {n:"Empanada gallega zamburiñas", u:"g", kcal:235},
  {n:"Filloas dulces", u:"ud", kcal:120},
  {n:"Filloas saladas", u:"ud", kcal:140},
  {n:"Marmitako bonito", u:"g", kcal:130},
  {n:"Bacalao al pil-pil", u:"g", kcal:220},
  {n:"Bacalao Vizcaína", u:"g", kcal:180},
  {n:"Pisto manchego", u:"g", kcal:90},
  {n:"Migas pastor", u:"g", kcal:300},
  {n:"Gachas manchegas", u:"g", kcal:230},
  {n:"Ajoblanco", u:"g", kcal:130},
  {n:"Porra antequerana", u:"g", kcal:160},
  {n:"Salmorejo cordobés", u:"g", kcal:130},
  {n:"Gazpacho andaluz", u:"g", kcal:50},
  {n:"Pescaíto frito mix", u:"g", kcal:220},
  {n:"Espinacas con garbanzos", u:"g", kcal:120},
  {n:"Albóndigas en salsa", u:"g", kcal:200},
  {n:"Carrilleras al vino", u:"g", kcal:240},
  {n:"Rabo de toro estofado", u:"g", kcal:260},
  {n:"Callos a la madrileña", u:"g", kcal:200},
  {n:"Magro con tomate", u:"g", kcal:180},
  {n:"Pollo al chilindrón", u:"g", kcal:170},
  {n:"Pollo en pepitoria", u:"g", kcal:180},
  {n:"Cordero al horno", u:"g", kcal:300},
  {n:"Cochinillo asado", u:"g", kcal:340},
  {n:"Bacalao al ajoarriero", u:"g", kcal:190},
  {n:"Patatas a la riojana", u:"g", kcal:130},
  {n:"Patatas a la importancia", u:"g", kcal:165},
  {n:"Patatas bravas", u:"g", kcal:200},
  {n:"Patatas alioli", u:"g", kcal:220},
  {n:"Ensaladilla rusa", u:"g", kcal:175},
  {n:"Ensalada César con pollo", u:"g", kcal:170},
  {n:"Ensalada mixta con atún", u:"g", kcal:90},
  {n:"Ensalada quinoa", u:"g", kcal:140},
  {n:"Tabulé", u:"g", kcal:140},
  {n:"Poke bowl salmón", u:"g", kcal:170},
  {n:"Bowl açaí frutas", u:"g", kcal:130},
  {n:"Buddha bowl vegetal", u:"g", kcal:140},
  {n:"Wrap pollo cesar", u:"ud", kcal:380},
  {n:"Bocadillo jamón serrano AOVE", u:"ud", kcal:420},
  {n:"Bocadillo lomo queso", u:"ud", kcal:550},
  {n:"Bocadillo tortilla", u:"ud", kcal:480},
  {n:"Sandwich mixto plancha", u:"ud", kcal:380},
  {n:"Sandwich vegetal", u:"ud", kcal:320},
  {n:"Tosta jamón serrano AOVE tomate", u:"ud", kcal:280},
  {n:"Tosta aguacate huevo poché", u:"ud", kcal:320},
  {n:"Pincho tortilla", u:"ud", kcal:180},
  {n:"Pintxo gilda", u:"ud", kcal:35},
  {n:"Banderilla", u:"ud", kcal:30},
  {n:"Boquerón en vinagre (1 ud)", u:"ud", kcal:18},
  {n:"Croqueta casera mediana", u:"ud", kcal:90},
  {n:"Buñuelo bacalao", u:"ud", kcal:70},
  {n:"Calamares a la romana ración", u:"g", kcal:175},
  {n:"Mejillones a la marinera", u:"g", kcal:120},

  // ===== AMPLIACIÓN: productos comerciales reconocibles (60) =====
  {n:"Activia natural Danone", u:"ud", kcal:55},
  {n:"Activia desnatado fresa", u:"ud", kcal:50},
  {n:"Actimel L. Casei", u:"ud", kcal:65},
  {n:"Skyr Lidl natural 150g", u:"ud", kcal:88},
  {n:"Yogur griego Hacendado 0%", u:"ud", kcal:75},
  {n:"Yogur proteína Danone 0%", u:"ud", kcal:80},
  {n:"Yopro batido proteína", u:"ud", kcal:135},
  {n:"Galletas Digestive avena Gullón", u:"ud", kcal:75},
  {n:"Tortitas arroz Bicentury", u:"ud", kcal:28},
  {n:"Pan Bimbo Silueta blanco", u:"ud", kcal:35},
  {n:"Pan Bimbo integral 100%", u:"ud", kcal:50},
  {n:"Pan Wasa fibra", u:"ud", kcal:28},
  {n:"Crackers Tuc clásico", u:"ud", kcal:23},
  {n:"Donuts clásico", u:"ud", kcal:230},
  {n:"Bollycao", u:"ud", kcal:235},
  {n:"Phoskitos", u:"ud", kcal:180},
  {n:"Pantera Rosa", u:"ud", kcal:245},
  {n:"Tigretón", u:"ud", kcal:200},
  {n:"Bony chocolate", u:"ud", kcal:140},
  {n:"Kit Kat 4 dedos", u:"ud", kcal:209},
  {n:"Twix barrita", u:"ud", kcal:248},
  {n:"Snickers", u:"ud", kcal:248},
  {n:"Mars", u:"ud", kcal:228},
  {n:"Bounty", u:"ud", kcal:268},
  {n:"M&Ms cacahuete bolsa 45g", u:"ud", kcal:235},
  {n:"M&Ms chocolate bolsa 45g", u:"ud", kcal:215},
  {n:"Lacasitos", u:"g", kcal:480},
  {n:"Conguitos", u:"g", kcal:530},
  {n:"Huesitos", u:"ud", kcal:108},
  {n:"Kinder bueno", u:"ud", kcal:243},
  {n:"Kinder chocolate barrita", u:"ud", kcal:114},
  {n:"Ferrero Rocher", u:"ud", kcal:73},
  {n:"Toblerone barrita 35g", u:"ud", kcal:185},
  {n:"Chocolate Valor 70% onza", u:"ud", kcal:55},
  {n:"Lindt 70% onza", u:"ud", kcal:55},
  {n:"Nutella tarrina porción 15g", u:"ud", kcal:80},
  {n:"Nocilla", u:"g", kcal:534},
  {n:"Cola Cao en polvo (15g)", u:"ud", kcal:57},
  {n:"Nesquik en polvo (13g)", u:"ud", kcal:50},
  {n:"Coca-Cola lata 330ml", u:"ud", kcal:139},
  {n:"Coca-Cola Zero lata 330ml", u:"ud", kcal:1},
  {n:"Fanta naranja lata 330ml", u:"ud", kcal:140},
  {n:"Aquarius limón 500ml", u:"ud", kcal:115},
  {n:"Red Bull 250ml", u:"ud", kcal:112},
  {n:"Monster Energy 500ml", u:"ud", kcal:225},
  {n:"Estrella Galicia 1906 botellín 330ml", u:"ud", kcal:175},
  {n:"Mahou 5 Estrellas tercio 330ml", u:"ud", kcal:152},
  {n:"Heineken tercio 330ml", u:"ud", kcal:142},
  {n:"Cruzcampo caña 200ml", u:"ud", kcal:80},
  {n:"Copa vino tinto Rioja 150ml", u:"ud", kcal:128},
  {n:"Copa cava brut 100ml", u:"ud", kcal:78},
  {n:"Vermut Martini rojo 100ml", u:"ud", kcal:145},
  {n:"Gin tonic estándar", u:"ud", kcal:200},
  {n:"Cubata ron cola", u:"ud", kcal:220},
  {n:"Whisky cola", u:"ud", kcal:230},
  {n:"Pan San Lidl integral semillas", u:"g", kcal:240},
  {n:"Pavo cocido Casa Tarradellas", u:"g", kcal:108},
  {n:"Jamón cocido extra Campofrío", u:"g", kcal:108},
  {n:"Atún claro aceite oliva Hacendado lata 80g", u:"ud", kcal:151},
  {n:"Mejillones escabeche Hacendado lata", u:"ud", kcal:172},
  {n:"Garbanzos cocidos bote Luengo 400g", u:"ud", kcal:480},

  // ===== AMPLIACIÓN: alimentos saludables / dieta (20) =====
  {n:"Caldo verduras casero claro", u:"g", kcal:10},
  {n:"Caldo huesos casero", u:"g", kcal:30},
  {n:"Caldo pollo ecológico", u:"g", kcal:12},
  {n:"Pollo a la plancha sin aceite", u:"g", kcal:135},
  {n:"Merluza al horno sin aceite", u:"g", kcal:80},
  {n:"Verduras al vapor mix", u:"g", kcal:40},
  {n:"Ensalada hojas variadas sin aliño", u:"g", kcal:18},
  {n:"Tortilla 2 claras + 1 yema", u:"ud", kcal:130},
  {n:"Tortilla 3 claras solo", u:"ud", kcal:80},
  {n:"Pechuga pavo plancha sin aceite", u:"g", kcal:135},
  {n:"Atún natural escurrido lata pequeña", u:"ud", kcal:65},
  {n:"Yogur skyr proteína sabores", u:"ud", kcal:90},
  {n:"Queso fresco batido 0% tarrina 250g", u:"ud", kcal:125},
  {n:"Avena con leche desnatada 40g", u:"ud", kcal:225},
  {n:"Porridge avena agua canela", u:"g", kcal:75},
  {n:"Bol açaí con plátano", u:"ud", kcal:280},
  {n:"Smoothie verde espinacas", u:"g", kcal:45},
  {n:"Crema de cacahuete sin azúcar 100% (15g)", u:"ud", kcal:90},
  {n:"Aguacate tosta 1/2 ud sobre pan integral", u:"ud", kcal:240},
  {n:"Salmón con verduras al horno (plato)", u:"g", kcal:160}
];
